### PR TITLE
Replace a naughty word with "something"

### PR DESCRIPTION
**Pull request by erbridge**

### CODE REVIEW

**Comment by zeke** [comment]
https://scribblediffusion.com/scribbles/i5wfkliaingmfaxngiisgipt2i

It works! Great idea.

**Comment by zeke** [comment]
The very last of the naughty word scribbles before this went live: https://scribblediffusion.com/scribbles/rq6c455zpjgnvbvbgvdsgkwuh4

**Comment by erbridge** [comment]
Ah damn. I was hoping it would be invisible to users. Still. Better than nothing.

**Comment by zeke** [comment]
Yeah the app is just using the prediction object for state, so there's no storing of one string and predicting with another.

**Pull request merged**
