### PR TITLE
use the replicate npm package

### PR DESCRIPTION
**Pull request by zeke**
https://github.com/replicate/replicate-js

Blocked by:

- https://github.com/replicate/replicate-js/issues/17

### CODE REVIEW

**Comment by zeke** [comment]
This is working locally but the preview app seems to be failing.

```
index-153743c76e8d4f30.js:1          POST https://scribble-diffusion-git-use-replicate-npm-package-replicate.vercel.app/api/predictions 500
```

**Comment by zeke** [comment]
```
$ vercel logs -f "https://scribble-diffusion-git-use-replicate-npm-package-replicate.vercel.app/"
```

Output:

```
2023-02-25T06:36:38.252Z  2023-02-25T06:36:38.837Z	c48daf0d-9fff-46cc-ac61-e7fb9411a31e	ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-fetch' imported from /var/task/node_modules/replicate/lib/ReplicateClient.js
2023-02-25T06:36:38.252Z      at new NodeError (node:internal/errors:393:5)
2023-02-25T06:36:38.252Z      at packageResolve (node:internal/modules/esm/resolve:865:9)
2023-02-25T06:36:38.252Z      at moduleResolve (node:internal/modules/esm/resolve:958:20)
2023-02-25T06:36:38.252Z      at moduleResolveWithNodePath (node:internal/modules/esm/resolve:909:12)
2023-02-25T06:36:38.252Z      at defaultResolve (node:internal/modules/esm/resolve:1173:79)
2023-02-25T06:36:38.252Z      at nextResolve (node:internal/modules/esm/loader:163:28)
2023-02-25T06:36:38.252Z      at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
2023-02-25T06:36:38.252Z      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
2023-02-25T06:36:38.252Z      at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
2023-02-25T06:36:38.252Z      at link (node:internal/modules/esm/module_job:75:36) {
2023-02-25T06:36:38.252Z    code: 'ERR_MODULE_NOT_FOUND'
2023-02-25T06:36:38.252Z  }
```

**Comment by zeke** [comment]
I wonder if https://github.com/vercel/fetch is injecting itself into this somehow and screwing things up...

**Comment by zeke** [comment]
@erbridge any idea what might be wrong here?

**Comment by erbridge** [comment]
> I wonder if https://github.com/vercel/fetch is injecting itself into this somehow and screwing things up...

It looks like that's supposed to use `node-fetch` under the hood anyway 🤔.

**Comment by erbridge** [comment]
Kicking off a redeploy seems to have cleared that error @zeke?

**Comment by zeke** [comment]
@erbridge no it's still broken when you try to create a scribble.

**Comment by gr2m** [comment]
I would recommend you remove the dependency on `node-fetch` altogether. All modern JavaScript runtimes, including Node LTS, come with a native fetch method now. The Replicate constructor should still accept a `fetch` option to use a custom fetch implementation for environments that don't bring their own, or for testing where we want to mock requests.

**Comment by zeke** [comment]
It looks like we're using other things from `node-fetch` besides just `fetch` like `FetchError`, `Response`, etc.

@gr2m can you point to any good reference implementations that are using built-in fetch?

**Comment by zeke** [comment]
Works on my machine. Now with webhooks. Thanks @erbridge for unblocking all the things.

```
🪝 received webhook for prediction:  prv72qvwdfcdxalsypyjjlruye
```

---

<a href="https://scribblediffusion.com/scribbles/prv72qvwdfcdxalsypyjjlruye">Screenshot 2023-03-09 at 9 07 55 PM<a/>

**Comment by zeke** [comment]
This is ready for a review.

**Pull request merged**
